routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login', 'LoginController@index')->name('login');
Route::get('logout', 'LoginController@logout')->name('logout');
Route::post('login/manual', 'LoginController@manualLogin')->name('login.manual');
Route::post('login/sso', 'LoginController@redirectToProvider')->name('login.sso');
Route::get('login/sso/callback', 'LoginController@handleProviderCallback');

/*
    Those are routes used to enforce consistency on the flow: all users must
    have valid keys, all reports must be signed
*/
Route::middleware('auth')->group(function () {
    Route::get('user/keys', 'UserController@generatekeys')->name('user.keys');
    Route::post('user/keys', 'UserController@savekeys')->name('user.savekeys');
    Route::get('user/getkey/{id}', 'UserController@getkey')->name('user.getkey');
    Route::get('user/{id}/keys/delete', 'UserController@askkeydestroy')->name('user.askkeydestroy');
    Route::delete('user/{id}/keys', 'UserController@deletekeys')->name('user.deletekeys');

    Route::get('history/{id}/sign', 'HistoryController@sign')->name('history.sign');
    Route::get('history/export', 'HistoryController@export')->name('history.export');

    Route::resource('history', 'HistoryController');
});

Route::middleware(['auth', 'enforce_flow'])->group(function () {
    Route::get('/', function() {
        return redirect()->route('notice.index');
    });

    Route::get('config/image', 'ConfigController@getImage')->name('config.image');

    Route::post('user/setpermission', 'UserController@setPermission')->name('user.setpermission');
    Route::get('user/{id}/delete', 'UserController@askdestroy')->name('user.askdestroy');
    Route::get('user/{id}/restore', 'UserController@restore')->name('user.restore');
    Route::post('user/import', 'UserController@import')->name('user.import');

    Route::get('category/{id}/delete', 'CategoryController@askdestroy')->name('category.askdestroy');

    Route::get('slot/{id}/delete', 'SlotController@askdestroy')->name('slot.askdestroy');
    Route::post('slot/{id}/attach', 'SlotController@attach')->name('slot.attach');

    Route::get('checklist/{id}/delete', 'ChecklistController@askdestroy')->name('checklist.askdestroy');

    Route::get('item/{id}/delete', 'ItemController@askdestroy')->name('item.askdestroy');
    Route::post('item/import', 'ItemController@import')->name('item.import');
    Route::get('item/import/sample', 'ItemController@importSample')->name('item.import.sample');

    Route::get('history/{id}/download', 'HistoryController@download')->name('history.download');

    Route::get('notice/admin', 'NoticeController@admin')->name('notice.admin');
    Route::get('notice/{id}/readcount', 'NoticeController@readcount')->name('notice.readcount');
    Route::get('notice/archive', 'NoticeController@archive')->name('notice.archive');
    Route::post('notice/{id}/read', 'NoticeController@read')->name('notice.read');
    Route::get('notice/{id}/delete', 'NoticeController@askdestroy')->name('notice.askdestroy');

    Route::resource('config', 'ConfigController');
    Route::resource('notice', 'NoticeController');
    Route::resource('user', 'UserController');
    Route::resource('category', 'CategoryController');
    Route::resource('slot', 'SlotController');
    Route::resource('checklist', 'ChecklistController');
    Route::resource('item', 'ItemController');
});

resources/views/app.blade.php
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="{{ mix('css/app.css') }}">
        <link rel="stylesheet" href="{{ asset('css/tempusdominus-bootstrap-4.css') }}">
        <link rel="stylesheet" href="{{ asset('css/summernote-bs4.css') }}">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>Spunta</title>
    </head>
    <body>
        @if(isset($no_menu) == false)
            @if(Auth::check())
                <div class="it-header-slim-wrapper mb-4">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-12">
                                <div class="it-header-slim-wrapper-content">
                                    <a class="d-none d-lg-block navbar-brand">{{ Auth::user()->name }}</a>
                                    <div class="nav-mobile">
                                        <nav aria-label="Navigazione accessoria">
                                            <a class="it-opener d-md-none" data-bs-toggle="collapse" href="#menu1a" role="button" aria-expanded="false" aria-controls="menu4">
                                                <span class="oi oi-menu"></span>
                                            </a>
                                            <div class="link-list-wrapper collapse" id="menu1a">
                                                <ul class="link-list">
                                                    <li>
                                                        <a class="list-item" href="{{ route('checklist.index') }}">{{ _i('Checklists') }}</a>
                                                    </li>

                                                    @if(Auth::user()->hasPermission('checklists'))
                                                        <li>
                                                            <a class="list-item" href="{{ route('category.index') }}">{{ _i('Admin') }}</a>
                                                        </li>
                                                    @endif

                                                    @if(Auth::user()->hasPermission('users'))
                                                        <li>
                                                            <a class="list-item" href="{{ route('user.index') }}">{{ _i('Users') }}</a>
                                                        </li>
                                                    @endif

                                                    @if(Auth::user()->hasPermission('checklists'))
                                                        <li>
                                                            <a class="list-item" href="{{ route('history.index') }}">{{ _i('Reports') }}</a>
                                                        </li>
                                                    @endif

                                                    @if(Auth::user()->hasPermission('notices'))
                                                        <li>
                                                            <a class="list-item" href="{{ route('notice.admin') }}">{{ _i('Notices') }}</a>
                                                        </li>
                                                    @else
                                                        <li>
                                                            <a class="list-item" href="{{ route('notice.index') }}">{{ _i('Notices') }}</a>
                                                        </li>
                                                    @endif

                                                    @if(Auth::user()->hasPermission('checklists'))
                                                        <li>
                                                            <a class="list-item" href="{{ route('config.index') }}">{{ _i('Configurations') }}</a>
                                                        </li>
                                                    @endif
                                                </ul>
                                            </div>
                                        </nav>
                                    </div>
                                    <div class="it-header-slim-right-zone">
                                        <form class="form-inline" method="GET" action="{{ route('logout') }}">
                                            <button class="btn btn-outline-danger bg-white" type="submit">{{ _i('Logout') }}</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            @endif
        @endif

        <div class="container mt-5">
            @yield('contents')
        </div>

        <script src="{{ mix('js/app.js') }}"></script>
    </body>
</html>

resources/views/login.blade.php
@extends('app')

@section('contents')
    <div class="row justify-content-center mt-4">
        <div class="col-12 col-md-6 text-center">
            @php
            $message = App\Config::getConfig('intro_message');
            @endphp

            @if(filled($message))
                <div class="alert alert-info mb-5">
                    {!! nl2br($message) !!}
                </div>
            @endif

            @switch(App\Config::getConfig('login'))
                @case('manual')
                    <form action="{{ route('login.manual') }}" method="POST">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="email">{{ _i('Email') }}</label>
                            <input type="email" class="form-control" name="email" id="email">
                        </div>
                        <div class="form-group">
                            <label for="password">{{ _i('Password') }}</label>
                            <input type="password" class="form-control" name="password" id="password">
                        </div>
                        <button type="submit" class="btn btn-primary">{{ _i('Login') }}</button>
                    </form>

                    @break

                @case('sso')
                    <form action="{{ route('login.sso') }}" method="POST">
                        {{ csrf_field() }}
                        <button type="submit" class="btn btn-primary">{{ _i('Login') }}</button>
                        <br>
                        <br>
                        <br>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" name="remember" id="remember">
                            <label for="remember">{{ _i('Do not logout from Google. Check this only if not working on a shared computer.') }}</label>
                        </div>
                    </form>

                    @break
            @endswitch
        </div>
    </div>
@endsection