routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login', 'LoginController@index')->name('login');
Route::get('logout', 'LoginController@logout')->name('logout');
Route::post('login/manual', 'LoginController@manualLogin')->name('login.manual');
Route::post('login/sso', 'LoginController@redirectToProvider')->name('login.sso');
Route::get('login/sso/callback', 'LoginController@handleProviderCallback');

/*
    Those are routes used to enforce consistency on the flow: all users must
    have valid keys, all reports must be signed
*/
Route::middleware('auth')->group(function () {
    Route::get('user/keys', 'UserController@generatekeys')->name('user.keys');
    Route::post('user/keys', 'UserController@savekeys')->name('user.savekeys');
    Route::get('user/getkey/{id}', 'UserController@getkey')->name('user.getkey');
    Route::get('user/{id}/keys/delete', 'UserController@askkeydestroy')->name('user.askkeydestroy');
    Route::delete('user/{id}/keys', 'UserController@deletekeys')->name('user.deletekeys');

    Route::get('history/{id}/sign', 'HistoryController@sign')->name('history.sign');
    Route::get('history/export', 'HistoryController@export')->name('history.export');

    Route::resource('history', 'HistoryController');
});

Route::middleware(['auth', 'enforce_flow'])->group(function () {
    Route::get('/', function() {
        return redirect()->route('notice.index');
    });

    Route::get('config/image', 'ConfigController@getImage')->name('config.image');

    Route::post('user/setpermission', 'UserController@setPermission')->name('user.setpermission');
    Route::get('user/{id}/delete', 'UserController@askdestroy')->name('user.askdestroy');
    Route::get('user/{id}/restore', 'UserController@restore')->name('user.restore');
    Route::post('user/import', 'UserController@import')->name('user.import');

    Route::get('category/{id}/delete', 'CategoryController@askdestroy')->name('category.askdestroy');

    Route::get('slot/{id}/delete', 'SlotController@askdestroy')->name('slot.askdestroy');
    Route::post('slot/{id}/attach', 'SlotController@attach')->name('slot.attach');

    Route::get('checklist/{id}/delete', 'ChecklistController@askdestroy')->name('checklist.askdestroy');

    Route::get('item/{id}/delete', 'ItemController@askdestroy')->name('item.askdestroy');
    Route::post('item/import', 'ItemController@import')->name('item.import');
    Route::get('item/import/sample', 'ItemController@importSample')->name('item.import.sample');

    Route::get('history/{id}/download', 'HistoryController@download')->name('history.download');

    Route::get('notice/admin', 'NoticeController@admin')->name('notice.admin');
    Route::get('notice/{id}/readcount', 'NoticeController@readcount')->name('notice.readcount');
    Route::get('notice/archive', 'NoticeController@archive')->name('notice.archive');
    Route::post('notice/{id}/read', 'NoticeController@read')->name('notice.read');
    Route::get('notice/{id}/delete', 'NoticeController@askdestroy')->name('notice.askdestroy');

    Route::resource('config', 'ConfigController');
    Route::resource('notice', 'NoticeController');
    Route::resource('user', 'UserController');
    Route::resource('category', 'CategoryController');
    Route::resource('slot', 'SlotController');
    Route::resource('checklist', 'ChecklistController');
    Route::resource('item', 'ItemController');
});

app/History.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use Log;
use PDF;
use Storage;

use ReportsDisk;

class History extends Model
{
    protected $dates = [
        'created_at',
        'updated_at',
        'date'
    ];

    public function user()
    {
        return $this->belongsTo('App\User')->withTrashed();
    }

    public function checklist()
    {
        return $this->belongsTo('App\Checklist')->withTrashed();
    }

    public function scopeCompleted($query)
    {
        $query->where('pending', false);
    }

    public function toPDF()
    {
        $filename = sprintf('report %s %s %s %s.pdf', $this->id, $this->date->toDateString(), $this->checklist->name, $this->user->name);

        if (global_multi_installation()) {
            $instance = instance_name();
            $path = $instance . '/' . $filename;
        }
        else {
            $path = $filename;
        }

        if (ReportsDisk::exists($path) == false) {
            $contents = nl2br($this->as_text);

            $logo_path = images_path() . 'logo.jpg';
            if (file_exists($logo_path)) {
                $contents = sprintf('<img src="%s"><br><br>', $logo_path) . $contents;
            }

            $pdf = PDF::loadHTML($contents)->output();
            ReportsDisk::put($path, $pdf);
        }

        return $path;
    }

    public function exportToJSON()
    {
        $filename = sprintf('report %s %s %s %s.json', $this->id, $this->date->toDateString(), $this->checklist->name, $this->user->name);

        if (global_multi_installation()) {
            $instance = instance_name();
            $path = $instance . '/' . $filename;
        }
        else {
            $path = $filename;
        }

        if (ReportsDisk::exists($path) == false) {
            $contents = json_encode([
                "id" => $this->id,
                "machine_readable" => json_decode($this->as_data, true),
                "signed" => $this->as_text,
            ]);
            ReportsDisk::put($path, $contents);
        }

        return $path;
    }
}

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Item extends Model implements MayHaveValue
{
    use SoftDeletes;

    public static function datatypes()
    {
        return [
            (object) [
                'value' => 'boolean',
                'label' => _i('True/False'),
                'notifiable' => true,
                'help' => _i("A simple selection to determine if the object is present or not (or if it has a specific attribute, defined in the name of the object)."),
            ],
            (object) [
                'value' => 'number',
                'label' => _i('Numeric'),
                'notifiable' => true,
                'help' => _i("A number to indicate a quantity, a level, a temperature or other attributes. If enabled, can generate a notification when the value if above or below a given threeshold."),
            ],
            (object) [
                'value' => 'text',
                'label' => _i('Short Text'),
                'notifiable' => true,
                'help' => _i("A short text field, to be used for a few words."),
            ],
            (object) [
                'value' => 'longtext',
                'label' => _i('Long Text'),
                'notifiable' => true,
                'help' => _i("A bigger text field, to be used for a note or a report."),
            ],
            (object) [
                'value' => 'datetime',
                'label' => _i('Date and Time'),
                'notifiable' => true,
                'help' => _i("Date and time, selectable by the operator."),
            ],
            (object) [
                'value' => 'select',
                'label' => _i('Choice'),
                'notifiable' => true,
                'help' => _i("To choose among a set of options, defined within the item. If enabled, can generate a notification when one or more specific options are selected."),
            ],
        ];
    }

    public static function importColumns()
    {
        $type_labels = [];
        foreach(Item::datatypes() as $datatype) {
            $type_labels[] = $datatype->label;
        }

        return [
            (object) [
                'label' => _i('Name'),
                'description' => _i('The name of the item'),
            ],
            (object) [
                'label' => _i('Help Text'),
                'description' => _i('An optional text to describe the item'),
            ],
            (object) [
                'label' => _i('Type'),
                'description' => _i('The type of the item. May be one of the following values: %s', [join(', ', $type_labels)]),
            ],
            (object) [
                'label' => _i('Options'),
                'description' => _i('Only if type is "Choice", define here a comma-separated list of selectable options'),
            ],
        ];
    }

    public static function datatype($type)
    {
        $types = self::datatypes();

        foreach($types as $t) {
            if ($t->value == $type) {
                return $t;
            }
        }

        return null;
    }

    public function evaluate($value)
    {
        $status = false;

        if ($this->notify == false) {
            return $status;
        }

        try {
            switch($this->type) {
                case 'boolean':
                    $status = ($value == $this->notificate->when);
                    break;

                case 'number':
                    if ($this->notificate->when == 'minor') {
                        $status = ($value <= $this->notificate->than);
                    }
                    else {
                        $status = ($value >= $this->notificate->than);
                    }
                    break;

                case 'select':
                    $status = in_array($value, $this->notificate->when);
                    break;

                case 'text':
                case 'longtext':
                    if ($this->notificate->when == 'empty') {
                        $status = empty($value);
                    }
                    else {
                        $status = !empty($value);
                    }

                    break;
            }
        }
        catch(\Exception $e) {
            \Log::error('Error in item evaluation: ' . $e->getMessage());
        }

        return $status;
    }

    public function getChoicesTextsAttribute()
    {
        $adjusted_contents = [];
        $ret = [];

        if ($this->type == 'select') {
            $data = json_decode($this->data);
            foreach($data as $d) {
                if (is_string($d)) {
                    $obj = (object)[
                        'text' => $d,
                        'notify' => false
                    ];

                    $adjusted_contents[] = $obj;
                    $d = $obj;
                }

                $ret[] = $d->text;
            }
        }

        if (!empty($adjusted_contents)) {
            $this->data = json_encode($adjusted_contents);
            $this->save();
        }

        return $ret;
    }

    public function getNotificateAttribute()
    {
        return json_decode($this->notification);
    }

    public function existingData($data)
    {
        if ($data) {
            foreach($data as $d) {
                if ($d->name == $this->name && isset($d->value) && filled($d->value)) {
                    switch($this->type) {
                        case 'boolean':
                            if ($d->value == 'false') {
                                return false;
                            }

                            break;

                        case 'select':
                            if ($d->value == _i('None Selected')) {
                                return false;
                            }

                            break;
                    }

                    return $d->value;
                }
            }
        }

        return false;
    }
}

resources/views/history/create.blade.php
@extends('app')

@section('contents')
    <?php

    if (isset($pending)) {
        $existing_data = json_decode($pending->as_data);
        $existing_data = $existing_data->contents ?? false;
        $pending_id = $pending->id;
    }
    else {
        $existing_data = false;
        $pending_id = 0;
    }

    ?>

    <form method="POST" action="{{ route('history.store') }}" class="checklist-create">
        @csrf

        <input type="hidden" name="checklist_id" value="{{ $checklist->id }}">
        <input type="hidden" name="pending_id" value="{{ $pending_id }}">

        <h1>{{ $checklist->name }}</h1>
        <hr>

        @foreach($checklist->slots as $slot)
            @include('history.slot', ['slot' => $slot, 'data' => $slot->existingData($existing_data)])
        @endforeach

        <hr>

        <button type="submit" class="btn btn-primary btn-lg btn-block" name="action" value="submit">{{ _i('Sign and Save') }}</button>
        <button type="submit" class="btn btn-info btn-md btn-block mt-4" name="action" value="pending">{{ _i('Temporary Save') }}</button>

        <hr>

        <a href="{{ route('checklist.index') }}" class="btn btn-sm btn-danger btn-md btn-block mt-4">{{ _i('Cancel and Back to Checklists') }}</a>

        <br>
    </form>
@endsection

resources/views/history/index.blade.php
@extends('app')

@section('contents')
    <form method="GET" action="{{ route('history.index') }}">
        <div class="row">
            <div class="col">
                <div class="form-group select-wrapper">
                    <label for="user_id">{{ _i('User') }}</label>
                    <select name="user_id" id="user_id" autocomplete="false">
                        <option value="-1" {{ $actual_user == -1 ? 'selected' : '' }}>{{ _i('None Selected') }}</option>

                        @foreach(App\User::orderBy('name', 'asc')->get() as $user)
                            <option value="{{ $user->id }}" {{ $actual_user == $user->id ? 'selected' : '' }}>{{ $user->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group select-wrapper">
                    <label for="checklist_id">{{ _i('Checklist') }}</label>
                    <select name="checklist_id" id="checklist_id" autocomplete="false">
                        <option value="-1" {{ $actual_checklist == -1 ? 'selected' : '' }}>{{ _i('None Selected') }}</option>

                        @foreach(App\Checklist::orderBy('name', 'asc')->get() as $checklist)
                            <option value="{{ $checklist->id }}" {{ $actual_checklist == $checklist->id ? 'selected' : '' }}>{{ $checklist->name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">{{ _i('Date From/To') }}</span>
                        </div>
                        <input id="search_start" type="date" class="form-control" name="start" value="{{ $actual_start }}">
                        <input id="search_end" type="date" class="form-control" name="end" value="{{ $actual_end }}">
                    </div>
                </div>
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">{{ _i('Hour From/To') }}</span>
                        </div>
                        <div class="select-wrapper">
                            <select name="hour_start">
                                <option value="-1" {{ $actual_hour_start == -1 ? 'selected' : '' }}>{{ _i('None Selected') }}</option>
                                @foreach(App\Checklist::availableHours() as $hours)
                                    <option value="{{ $hours }}" {{ $actual_hour_start == $hours ? 'selected' : '' }}>{{ $hours }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="select-wrapper">
                            <select name="hour_end">
                                <option value="-1" {{ $actual_hour_end == -1 ? 'selected' : '' }}>{{ _i('None Selected') }}</option>
                                @foreach(App\Checklist::availableHours() as $hours)
                                    <option value="{{ $hours }}" {{ $actual_hour_end == $hours ? 'selected' : '' }}>{{ $hours }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-12">
                        <button type="submit" class="btn btn-success float-end">{{ _i('Search') }}</button>
                    </div>
                </div>
            </div>
        </div>
    </form>

    <hr>

    <div class="row">
        <div class="col">
            @if($reports->isEmpty())
                <div class="alert alert-info">
                    <p>
                        {{ _i('There are no reports, yet.') }}
                    </p>
                </div>
            @else
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th width="25%">{{ _i('User') }}</th>
                                <th width="25%">{{ _i('Checklist') }}</th>
                                <th width="25%">{{ _i('Date') }}</th>
                                <th width="5%">{{ _i('Status') }}</th>
                                <th width="20%">&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($reports as $report)
                                <tr>
                                    <td>{{ $report->user->name }}</td>

                                    <td>
                                        {{ $report->checklist->name }}
                                        @if($report->checklist->trashed())
                                            {{ _i(' (Deleted)') }}
                                        @endif
                                    </td>

                                    <td>{{ printableDateTime($report->date) }}</td>

                                    <td>
                                        @if($report->status)
                                            <span class="oi oi-check" title="{{ _i('Complete') }}"></span>
                                        @else
                                            <span class="oi oi-ban" title="{{ _i('Anomalies') }}"></span>
                                        @endif

                                        @if($report->checklist->inTime($report->date) == false)
                                            <span class="oi oi-clock" title="{{ _i('Expired') }}"></span>
                                        @endif

                                        @if($report->signed == false)
                                            <span class="oi oi-warning" title="{{ _i('Not Signed') }}"></span>
                                        @endif
                                    </td>
                                    <td>
                                        <span class="action-icons float-end">
                                            <a href="{{ route('history.show', $report->id) }}"><span class="oi oi-magnifying-glass" title="{{ _i('Show Report') }}"></span></a>
                                            <a href="{{ route('history.download', $report->id) }}"><span class="oi oi-data-transfer-download" title="{{ _i('Download') }}"></span></a>
                                        </span>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>

                {!! $reports->links() !!}
            @endif
        </div>
    </div>

    <div class="row">
        <div class="col">
            <a href="{{ route('history.export', ['user_id' => $actual_user, 'checklist_id' => $actual_checklist, 'start' => $actual_start, 'end' => $actual_end, 'hour_start' => $actual_hour_start, 'hour_end' => $actual_hour_end]) }}" class="btn btn-success float-end">{{ _i('Export CSV') }}</a>
        </div>
    </div>
@endsection

resources/views/history/show.blade.php
@extends('app')

@section('contents')
    <div class="row">
        <div class="col">
            <h2>{{ $report->checklist->name }}</h2>
            <h2>{{ $report->user->name }}</h2>
            <h2>{{ $report->date }}</h2>

            <br>

            <table class="table">
                <?php $data = json_decode($report->as_data) ?>
                @include('history.staticslot', ['master' => $data, 'deep' => 0])
            </table>
        </div>
        <div class="col">
            <div class="card bg-light">
                <div class="card-header">{{ _i('Signed Version') }}</div>
                <div class="card-body">
                    <p class="card-text">
                        <pre>{{ $report->as_text }}</pre>
                    </p>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/history/sign.blade.php
@extends('app')

@section('contents')
    <div class="row">
        <div class="col">
            <p>
                {{ _i('Please input your PIN to sign the filled checklist.') }}
            </p>
        </div>
    </div>

    <input type="hidden" name="privkey" id="privkey" value="{{ $user->privkey }}">
    <input type="hidden" name="cleartext" id="cleartext" value="{{ $report->as_text }}">

    <div class="row">
        <div class="col">
            <p id="please-wait" hidden>
                {{ _i('Please wait...') }}
            </p>

            <p id="error-msg" class="alert alert-danger" hidden>
                {{ _i('Invalid PIN, please retry') }}
            </p>

            <form method="PUT" action="{{ route('history.update', $report->id) }}" class="sign_document">
                <div class="form-group">
                    <label for="pin">{{ _i('PIN') }}</label>
                    <input type="password" class="form-control form-control-lg" name="pin" id="pin" required autocomplete="false" minlength="5" maxlength="5">
                </div>

                <div class="form-group row">
                    <div class="col-sm-8 col-sm-offset-4">
                        <button type="submit" class="btn btn-success btn-lg">{{ _i('Save') }}</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <br><br><br><br>

    <div class="row">
        <div class="col">
            <span class="btn btn-danger oi oi-key async-modal-edit" title="{{ _i('Reset Sign Key') }}" data-edit-url="{{ route('user.askkeydestroy', $user->id) }}"> {{ _i('Ask key reset') }}</span>
        </div>
    </div>
@endsection

resources/views/history/slot.blade.php
<h2 class="mt-4">{{ $slot->name }}</h2>

<ul class="list-group">
    @foreach($slot->contents as $content)
        @if(is_a($content, 'App\Slot'))
            <li class="list-group-item">
                @include('history.slot', ['slot' => $content, 'data' => $content->existingData($data)])
            </li>
        @elseif(is_a($content, 'App\Item'))
            <?php

            $value = $content->existingData($data);

            if ($value) {
                $wrapper_class = 'success';
            }
            else if ($content->type == 'text' || $content->type == 'longtext' || $content->type == 'freetext') {
                $wrapper_class = 'default';
            }
            else {
                $wrapper_class = 'danger';
            }

            ?>

            <li class="list-group-item list-group-item-{{ $wrapper_class }} checklist-filling-row">
                <div class="row">
                    <div class="col">
                        <p>{{ $content->name }}</p>
                        @if(!empty($content->help))
                            <small>{{ $content->help }}</small>
                        @endif

                        @if($content->type == 'longtext' || $content->type == 'freetext')
                            <textarea class="form-control form-control-lg" name="item_{{ $content->id }}_slot_{{ $slot->id }}" rows="5">{{ $value }}</textarea>
                        @endif
                    </div>

                    @if($content->type != 'longtext' && $content->type != 'freetext')
                        <div class="col">
                            @if($content->type == 'boolean')
                                <div class="btn-group btn-group-toggle btn-group-lg float-end">
                                    <label class="btn {{ $value == 'true' ? 'active btn-success' : 'btn-light' }}">
                                        <input type="radio" class="btn-check" name="item_{{ $content->id }}" value="true" autocomplete="off" {{ $value == 'true' ? 'checked' : '' }}> {{ _i('YES') }}
                                    </label>
                                    <label class="btn {{ $value != 'true' ? 'active btn-danger' : 'btn-light' }}">
                                        <input type="radio" class="btn-check" name="item_{{ $content->id }}" value="false" autocomplete="off" {{ $value != 'true' ? 'checked' : '' }}> {{ _i('NO') }}
                                    </label>
                                </div>
                            @elseif($content->type == 'number')
                                <input type="number" class="form-control form-control-lg" name="item_{{ $content->id }}_slot_{{ $slot->id }}" value="{{ $value ? $value : 0 }}" autocomplete="false">
                            @elseif($content->type == 'text')
                                <input type="text" class="form-control form-control-lg" name="item_{{ $content->id }}_slot_{{ $slot->id }}" autocomplete="false" value="{{ $value }}">
                            @elseif($content->type == 'datetime')
                                <input type="datetime-local" class="form-control form-control-lg" name="item_{{ $content->id }}_slot_{{ $slot->id }}" autocomplete="false" value="{{ $value }}">
                            @elseif($content->type == 'select')
                                <select class="form-control form-control-lg" name="item_{{ $content->id }}_slot_{{ $slot->id }}" autocomplete="false">
                                    <option value="{{ _i('None Selected') }}">{{ _i('None Selected') }}</option>
                                    @foreach($content->choices_texts as $option)
                                        <option value="{{ $option }}" {{ $value == $option ? 'selected' : '' }}>{{ $option }}</option>
                                    @endforeach
                                </select>
                            @endif
                        </div>
                    @endif
                </div>
            </li>
        @endif
    @endforeach
</ul>

resources/views/history/staticslot.blade.php
@if(isset($master->slots))
    @foreach($master->slots as $slot)
        <tr>
            <th colspan="3">
                {!! str_repeat('-', $deep * 2) !!} {{ $slot->name }}
            </th>
        </tr>
        @foreach($slot->items as $item)
            <tr class="{{ $item->status == false ? 'table-danger' : '' }}">
                <td>{{ $item->name }}</td>
                <td>{{ $item->value }}</td>
                <td>
                    @if($item->status)
                        <span class="oi oi-check"></span>
                    @else
                        <span class="oi oi-ban"></span>
                    @endif
                </td>
            </tr>
        @endforeach

        @include('history.staticslot', ['master' => $slot, 'deep' => $deep + 1])
    @endforeach
@else
    @foreach($master->contents as $content)
        @if(isset($content->contents))
            <tr>
                <th colspan="3">
                    {!! str_repeat('-', $deep * 2) !!} {{ $content->name }}
                </th>
            </tr>

            @include('history.staticslot', ['master' => $content, 'deep' => $deep + 1])
        @else
            <tr class="{{ $content->status == false ? 'table-danger' : '' }}">
                <td>{{ $content->name }}</td>
                <td>{{ $content->value }}</td>
                <td>
                    @if($content->status)
                        <span class="oi oi-check"></span>
                    @else
                        <span class="oi oi-ban"></span>
                    @endif
                </td>
            </tr>
        @endif
    @endforeach
@endif