routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login', 'LoginController@index')->name('login');
Route::get('logout', 'LoginController@logout')->name('logout');
Route::post('login/manual', 'LoginController@manualLogin')->name('login.manual');
Route::post('login/sso', 'LoginController@redirectToProvider')->name('login.sso');
Route::get('login/sso/callback', 'LoginController@handleProviderCallback');

/*
    Those are routes used to enforce consistency on the flow: all users must
    have valid keys, all reports must be signed
*/
Route::middleware('auth')->group(function () {
    Route::get('user/keys', 'UserController@generatekeys')->name('user.keys');
    Route::post('user/keys', 'UserController@savekeys')->name('user.savekeys');
    Route::get('user/getkey/{id}', 'UserController@getkey')->name('user.getkey');
    Route::get('user/{id}/keys/delete', 'UserController@askkeydestroy')->name('user.askkeydestroy');
    Route::delete('user/{id}/keys', 'UserController@deletekeys')->name('user.deletekeys');

    Route::get('history/{id}/sign', 'HistoryController@sign')->name('history.sign');
    Route::get('history/export', 'HistoryController@export')->name('history.export');

    Route::resource('history', 'HistoryController');
});

Route::middleware(['auth', 'enforce_flow'])->group(function () {
    Route::get('/', function() {
        return redirect()->route('notice.index');
    });

    Route::get('config/image', 'ConfigController@getImage')->name('config.image');

    Route::post('user/setpermission', 'UserController@setPermission')->name('user.setpermission');
    Route::get('user/{id}/delete', 'UserController@askdestroy')->name('user.askdestroy');
    Route::get('user/{id}/restore', 'UserController@restore')->name('user.restore');
    Route::post('user/import', 'UserController@import')->name('user.import');

    Route::get('category/{id}/delete', 'CategoryController@askdestroy')->name('category.askdestroy');

    Route::get('slot/{id}/delete', 'SlotController@askdestroy')->name('slot.askdestroy');
    Route::post('slot/{id}/attach', 'SlotController@attach')->name('slot.attach');

    Route::get('checklist/{id}/delete', 'ChecklistController@askdestroy')->name('checklist.askdestroy');

    Route::get('item/{id}/delete', 'ItemController@askdestroy')->name('item.askdestroy');
    Route::post('item/import', 'ItemController@import')->name('item.import');
    Route::get('item/import/sample', 'ItemController@importSample')->name('item.import.sample');

    Route::get('history/{id}/download', 'HistoryController@download')->name('history.download');

    Route::get('notice/admin', 'NoticeController@admin')->name('notice.admin');
    Route::get('notice/{id}/readcount', 'NoticeController@readcount')->name('notice.readcount');
    Route::get('notice/archive', 'NoticeController@archive')->name('notice.archive');
    Route::post('notice/{id}/read', 'NoticeController@read')->name('notice.read');
    Route::get('notice/{id}/delete', 'NoticeController@askdestroy')->name('notice.askdestroy');

    Route::resource('config', 'ConfigController');
    Route::resource('notice', 'NoticeController');
    Route::resource('user', 'UserController');
    Route::resource('category', 'CategoryController');
    Route::resource('slot', 'SlotController');
    Route::resource('checklist', 'ChecklistController');
    Route::resource('item', 'ItemController');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes;

    public function checklists()
    {
        return $this->hasMany('App\Checklist')->orderBy('sorting');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Category;
use App\Item;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->permissionAccess('checklists');
        $categories = Category::orderBy('sorting')->get();
        $items = Item::orderBy('name')->get();
        $active_tab = $request->input('tab', 'categories');
        $active_checklist = $request->input('checklist', '-1');
        return view('category.index', compact('active_tab', 'active_checklist', 'categories', 'items'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->permissionAccess('checklists');

        $category = new Category();
        $category->name = $request->input('name');
        $category->save();

        return redirect()->route('category.index', ['tab' => 'categories']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $this->permissionAccess('checklists');
        $category = Category::findOrFail($id);
        return view('category.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->permissionAccess('checklists');
        $category = Category::findOrFail($id);
        return view('category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->permissionAccess('checklists');

        $saving_type = $request->input('saving_type', '');

        switch($saving_type) {
            case 'sort_categories':
                $index = 1;
                $ids = $request->input('ids');
                foreach ($ids as $id) {
                    $category = Category::findOrFail($id);
                    $category->sorting = $index;
                    $category->save();
                    $index++;
                }
                break;

            case 'sort_checklists':
                $category = Category::findOrFail($id);

                $index = 1;
                $ids = $request->input('ids');
                foreach ($ids as $id) {
                    $category->checklists()->where('id', $id)->update(['sorting' => $index]);
                    $index++;
                }
                break;

            default:
                $category = Category::findOrFail($id);
                $category->name = $request->input('name');
                $category->save();
                return redirect()->route('category.index', ['tab' => 'categories']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->permissionAccess('checklists');
        $category = Category::findOrFail($id);
        $category->checklists()->delete();
        $category->delete();
        return redirect()->route('category.index', ['tab' => 'categories']);
    }

    public function askdestroy($id)
    {
        $this->permissionAccess('checklists');
        $category = Category::findOrFail($id);
        return view('category.destroy', compact('category'));
    }
}

resources/views/category/admin.blade.php
<div class="row">
    <div class="col">
        <button type="button" class="btn btn-primary float-end" data-bs-toggle="modal" data-bs-target="#createCategory">{{ _i('Create New Category') }}</button>
        <div class="clearfix"></div>
    </div>
</div>

@if($categories->isEmpty())
    <hr>

    <div class="alert alert-info">
        <p>
            {{ _i('There are not categories.') }}
        </p>
        <p>
            {{ _i("Categories are collection of checklists, to assign them to referents in block. Click on 'Create New Category' to create a new one, and then create your first checklist!") }}
        </p>
        <p>
            {{ _i('It is required at least one category to create checklists.') }}
        </p>
    </div>
@else
    <div class="sortable" data-sorted-handler=".sorting-categories" data-sorted-callback="updateCategories" data-update-url="{{ route('category.update', 0) }}">
        @foreach($categories as $category)
            <div class="row category-row" data-category-id="{{ $category->id }}" data-update-url="{{ route('category.update', $category->id) }}">
                <div class="col-12 col-md-6">
                    <p class="display-5">{{ $category->name }}</p>
                    <span class="action-icons">
                        <span class="oi oi-pencil async-modal-edit" title="{{ _i('Edit Category') }}" data-edit-url="{{ route('category.edit', $category->id) }}"></span>
                        <span class="oi oi-trash async-modal-edit" title="{{ _i('Delete Category') }}" data-edit-url="{{ route('category.askdestroy', $category->id) }}"></span>
                        <span class="oi oi-resize-height sorting-categories" title="{{ _i('Drag to sort') }}"></span>
                    </span>
                </div>
                <div class="col-12 col-md-6">
                    <ul class="list-group sortable" data-sorted-callback="updateChecklists">
                        @foreach($category->checklists as $checklist)
                            <li class="list-group-item" data-checklist-id="{{ $checklist->id }}">
                                <span class="name">{{ $checklist->name }}</span>
                                <span class="action-icons float-end">
                                    <span class="oi oi-pencil async-modal-edit" title="{{ _i('Edit Checklist') }}" data-edit-url="{{ route('checklist.edit', $checklist->id) }}"></span>
                                    <span class="oi oi-trash async-modal-edit" title="{{ _i('Delete Checklist') }}" data-edit-url="{{ route('checklist.askdestroy', $checklist->id) }}"></span>
                                    <span class="oi oi-loop-square async-modal-edit" title="{{ _i('Duplicate Checklist') }}" data-edit-url="{{ route('checklist.create', ['original' => $checklist->id]) }}"></span>
                                    <span class="oi oi-resize-height" title="{{ _i('Drag to Sort') }}"></span>
                                </span>
                            </li>
                        @endforeach
                    </ul>

                    <button type="button" class="list-group-item list-group-item-action list-group-item-primary btn-sm" data-bs-toggle="modal" data-bs-target="#createChecklist-{{ $category->id }}">{{ _i('Add a Checklist in Category %s', [$category->name]) }}</button>
                    @include('checklist.edit', ['category' => $category, 'checklist' => null])
                </div>
            </div>
        @endforeach
    </div>
@endif

@include('category.edit', ['category' => null])

resources/views/category/destroy.blade.php
<div class="modal fade" id="destroyChecklist-{{ $category->id }}" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">{{ _i('Delete Category') }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{{ route('category.destroy', $category->id) }}" method="POST">
                {{ csrf_field() }}
                <input type="hidden" name="_method" value="DELETE">
                <div class="modal-body">
                    <p>
                        {{ _i('Are you really sure you want to delete category %s and all related checklists?', $category->name) }}
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{{ _i('Close') }}</button>
                    <button type="submit" class="btn btn-danger">{{ _i('Delete Category') }}</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/category/edit.blade.php
<?php

if (isset($category) && $category != null) {
    $modal_id = sprintf('editCategory-', $category->id);
    $modal_label = _i('Edit Category');
    $form_url = route('category.update', $category->id);
    $form_method = 'PUT';
    $actual_name = $category->name;
}
else {
    $modal_id = 'createCategory';
    $modal_label = _i('Create Category');
    $form_url = route('category.store');
    $form_method = 'POST';
    $actual_name = '';
}

?>

<div class="modal fade" id="{{ $modal_id }}" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">{{ $modal_label }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{{ $form_url }}" method="POST">
                {{ csrf_field() }}
                <input type="hidden" name="_method" value="{{ $form_method }}">

                <div class="modal-body">
                    <div class="form-group">
                        <label for="name">{{ _i('Name') }}</label>
                        <input type="text" class="form-control" name="name" id="name" value="{{ $actual_name }}" required autocomplete="false">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{{ _i('Close') }}</button>
                    <button type="submit" class="btn btn-success">{{ _i('Save') }}</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/category/index.blade.php
@extends('app')

@section('contents')
    <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item">
            <a class="nav-link {{ $active_tab == 'categories' ? 'active' : '' }}" data-bs-toggle="tab" href="#categories-tab" role="tab">{{ _i('Categories and Checklists') }}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {{ $active_tab == 'items' ? 'active' : '' }}" data-bs-toggle="tab" href="#items-tab" role="tab">{{ _i('Items') }}</a>
        </li>
        <li class="nav-item d-none d-md-block">
            <a class="nav-link {{ $active_tab == 'distribution' ? 'active' : '' }}" data-bs-toggle="tab" href="#distribution-tab" role="tab">{{ _i('Distribution') }}</a>
        </li>
    </ul>

    <div class="tab-content">
        <div class="tab-pane fade show {{ $active_tab == 'categories' ? 'active' : '' }}" id="categories-tab" role="tabpanel">
            <br>
            @include('category.admin')
        </div>

        <div class="tab-pane fade show {{ $active_tab == 'items' ? 'active' : '' }}" id="items-tab" role="tabpanel">
            <br>
            @include('item.admin')
        </div>

        <div class="tab-pane fade show {{ $active_tab == 'distribution' ? 'active' : '' }}" id="distribution-tab" role="tabpanel">
            <br>
            @include('checklist.show', ['checklist' => App\Checklist::find($active_checklist)])
        </div>
    </div>
@endsection