routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login', 'LoginController@index')->name('login');
Route::get('logout', 'LoginController@logout')->name('logout');
Route::post('login/manual', 'LoginController@manualLogin')->name('login.manual');
Route::post('login/sso', 'LoginController@redirectToProvider')->name('login.sso');
Route::get('login/sso/callback', 'LoginController@handleProviderCallback');

/*
    Those are routes used to enforce consistency on the flow: all users must
    have valid keys, all reports must be signed
*/
Route::middleware('auth')->group(function () {
    Route::get('user/keys', 'UserController@generatekeys')->name('user.keys');
    Route::post('user/keys', 'UserController@savekeys')->name('user.savekeys');
    Route::get('user/getkey/{id}', 'UserController@getkey')->name('user.getkey');
    Route::get('user/{id}/keys/delete', 'UserController@askkeydestroy')->name('user.askkeydestroy');
    Route::delete('user/{id}/keys', 'UserController@deletekeys')->name('user.deletekeys');

    Route::get('history/{id}/sign', 'HistoryController@sign')->name('history.sign');
    Route::get('history/export', 'HistoryController@export')->name('history.export');

    Route::resource('history', 'HistoryController');
});

Route::middleware(['auth', 'enforce_flow'])->group(function () {
    Route::get('/', function() {
        return redirect()->route('notice.index');
    });

    Route::get('config/image', 'ConfigController@getImage')->name('config.image');

    Route::post('user/setpermission', 'UserController@setPermission')->name('user.setpermission');
    Route::get('user/{id}/delete', 'UserController@askdestroy')->name('user.askdestroy');
    Route::get('user/{id}/restore', 'UserController@restore')->name('user.restore');
    Route::post('user/import', 'UserController@import')->name('user.import');

    Route::get('category/{id}/delete', 'CategoryController@askdestroy')->name('category.askdestroy');

    Route::get('slot/{id}/delete', 'SlotController@askdestroy')->name('slot.askdestroy');
    Route::post('slot/{id}/attach', 'SlotController@attach')->name('slot.attach');

    Route::get('checklist/{id}/delete', 'ChecklistController@askdestroy')->name('checklist.askdestroy');

    Route::get('item/{id}/delete', 'ItemController@askdestroy')->name('item.askdestroy');
    Route::post('item/import', 'ItemController@import')->name('item.import');
    Route::get('item/import/sample', 'ItemController@importSample')->name('item.import.sample');

    Route::get('history/{id}/download', 'HistoryController@download')->name('history.download');

    Route::get('notice/admin', 'NoticeController@admin')->name('notice.admin');
    Route::get('notice/{id}/readcount', 'NoticeController@readcount')->name('notice.readcount');
    Route::get('notice/archive', 'NoticeController@archive')->name('notice.archive');
    Route::post('notice/{id}/read', 'NoticeController@read')->name('notice.read');
    Route::get('notice/{id}/delete', 'NoticeController@askdestroy')->name('notice.askdestroy');

    Route::resource('config', 'ConfigController');
    Route::resource('notice', 'NoticeController');
    Route::resource('user', 'UserController');
    Route::resource('category', 'CategoryController');
    Route::resource('slot', 'SlotController');
    Route::resource('checklist', 'ChecklistController');
    Route::resource('item', 'ItemController');
});

app/Checklist.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

use App\Config;

class Checklist extends Model
{
    use SoftDeletes;

    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function slots()
    {
        return $this->hasMany('App\Slot')->where('parent_id', 0)->orderBy('sorting');
    }

    public function histories()
    {
        return $this->hasMany('App\History')->orderBy('date', 'desc');
    }

    public function hasHour($day, $hour)
    {
        if (Config::getConfig('checklist_times') == false) {
            return false;
        }
        else {
            $info = json_decode($this->hours);
            if (isset($info->$day) == false) {
                return false;
			}
            else {
                return in_array($hour, $info->$day);
			}
        }
    }

    public function inTime($date = null)
    {
        if (Config::getConfig('checklist_times') == false) {
            return true;
		}

        if ($date == null) {
            $time = time();
        }
        else {
            $time = strtotime($date);
        }

		$today = mb_strtolower(date('D', $time));
		$now = date('H', $time);
        return $this->hasHour($today, sprintf('%02d:00', $now));
    }

    public static function availableDays()
    {
        return [
            'mon' => _i('Mon'),
            'tue' => _i('Tue'),
            'wed' => _i('Wed'),
            'thu' => _i('Thu'),
            'fri' => _i('Fri'),
            'sat' => _i('Sat'),
            'sun' => _i('Sun'),
        ];
    }

    public static function availableHours()
    {
        $ret = [];

        for($i = 0; $i < 24; $i++) {
            $ret[] = sprintf('%02d:00', $i);
		}

        return $ret;
    }
}

app/Http/Controllers/ChecklistController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Session;
use Auth;

use App\Category;
use App\History;
use App\Checklist;
use App\Slot;
use App\Item;
use App\Config;

class ChecklistController extends Controller
{
    public function index(Request $request)
    {
        $user_id = $request->user()->id;
        $categories = Category::orderBy('sorting', 'asc')->get();
        $pending = History::where('user_id', $user_id)->where('pending', true)->orderBy('created_at', 'desc')->get();
        return view('checklist.index', compact('categories', 'pending'));
    }

    public function create(Request $request)
    {
        $this->permissionAccess('checklists');
        $id = $request->input('original');
        $checklist = Checklist::findOrFail($id);
        return view('checklist.duplicate', compact('checklist'));
    }

    private function readHours($checklist, $request)
    {
        if (Config::getConfig('checklist_times')) {
            $hours = $request->input('hours');

            $to_save = (object)[];
            foreach(Checklist::availableDays() as $day => $label)
                $to_save->$day = [];

            foreach($hours as $h) {
                list($day, $hour) = explode('_', $h);
                $to_save->$day[] = $hour;
            }

            $checklist->hours = json_encode($to_save);
        }
        else {
            $checklist->hours = '[]';
        }
    }

    private function recursiveReplicate($oslot, $parent, $checklist)
    {
        $slot = $oslot->replicate();
        $slot->checklist_id = $checklist->id;
        $slot->parent_id = ($parent == null) ? 0 : $parent->id;
        $slot->save();

        foreach($oslot->items as $item) {
            $slot->items()->attach($item->id, ['sorting' => $item->pivot->sorting]);
        }

        foreach($oslot->slots as $subslot) {
            $this->recursiveReplicate($subslot, $slot, $checklist);
        }
    }

    public function store(Request $request)
    {
        $this->permissionAccess('checklists');

        $original_checklist = $request->input('original_checklist', null);

        if ($original_checklist == null) {
            $category_id = $request->input('category_id');
            $category = Category::findOrFail($category_id);

            $checklist = new Checklist();
            $checklist->name = $request->input('name');
            $checklist->category_id = $category_id;
            $checklist->notices_recipient = $request->input('notices_recipient');
            $checklist->sorting = $category->checklists()->count() + 1;
            $this->readHours($checklist, $request);
            $checklist->save();

            $slot = new Slot();
            $slot->name = 'Default';
            $slot->checklist_id = $checklist->id;
            $slot->save();
        }
        else {
            $original = Checklist::find($original_checklist);
            $checklist = $original->replicate();
            $checklist->name = $request->input('name');
            $checklist->save();

            foreach ($original->slots as $oslot) {
                $this->recursiveReplicate($oslot, null, $checklist);
            }
        }

        return redirect()->route('category.index', ['tab' => 'categories']);
    }

    public function show($id)
    {
        return redirect()->route('category.index', ['tab' => 'distribution', 'checklist' => $id]);
    }

    public function edit($id)
    {
        $this->permissionAccess('checklists');
        $checklist = Checklist::findOrFail($id);
        return view('checklist.edit', compact('checklist'));
    }

    public function update(Request $request, $id)
    {
        $this->permissionAccess('checklists');

        $checklist = Checklist::findOrFail($id);
        $saving_type = $request->input('saving_type', '');

        switch($saving_type) {
            case 'sort_slots':
                $index = 1;
                $ids = $request->input('ids');
                foreach ($ids as $id) {
                    $checklist->slots()->where('id', $id)->update(['sorting' => $index]);
                    $index++;
                }
                break;

            default:
                $checklist->name = $request->input('name');
                $checklist->notices_recipient = $request->input('notices_recipient');
                $this->readHours($checklist, $request);
                $checklist->save();
                return redirect()->route('category.index', ['tab' => 'categories']);
        }
    }

    public function destroy($id)
    {
        $this->permissionAccess('checklists');
        Checklist::findOrFail($id)->delete();
        return redirect()->route('category.index', ['tab' => 'categories']);
    }

    public function askdestroy($id)
    {
        $this->permissionAccess('checklists');
        $checklist = Checklist::findOrFail($id);
        return view('checklist.destroy', compact('checklist'));
    }
}

resources/views/checklist/destroy.blade.php
<div class="modal fade" id="destroyChecklist-{{ $checklist->id }}" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">{{ _i('Delete Checklist') }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{{ route('checklist.destroy', $checklist->id) }}" method="POST">
                {{ csrf_field() }}
                <input type="hidden" name="_method" value="DELETE">
                <div class="modal-body">
                    <p>
                        {{ _i('Are you really sure you want to delete checklist %s?', $checklist->name) }}
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{{ _i('Close') }}</button>
                    <button type="submit" class="btn btn-danger">{{ _i('Delete Checklist') }}</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/checklist/duplicate.blade.php
<div class="modal fade" id="destroyChecklist-{{ $checklist->id }}" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">{{ _i('Duplicate Checklist') }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{{ route('checklist.store') }}" method="POST">
                {{ csrf_field() }}
                <input type="hidden" name="original_checklist" value="{{ $checklist->id }}">
                <div class="modal-body">
                    <div class="form-group row">
                        <label for="new_name">{{ _i('Name') }}</label>
                        <input type="text" class="form-control" name="name" id="new_name" value="{{ _i('Copy of %s', $checklist->name) }}" required autocomplete="false">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{{ _i('Close') }}</button>
                    <button type="submit" class="btn btn-success">{{ _i('Save') }}</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/checklist/edit.blade.php
<?php

if (isset($checklist) && $checklist != null) {
    $modal_id = sprintf('editChecklist-%s', $checklist->id);
    $modal_label = _i('Edit Checklist');
    $form_url = route('checklist.update', $checklist->id);
    $form_method = 'PUT';
    $actual_name = $checklist->name;
    $actual_referent = $checklist->notices_recipient;
    $category_id = $checklist->category_id;
}
else {
    $checklist = null;
    $modal_id = sprintf('createChecklist-%s', $category->id);
    $modal_label = _i('Create Checklist');
    $form_url = route('checklist.store');
    $form_method = 'POST';
    $actual_name = '';
    $actual_referent = '';
    $category_id = $category->id;
}

?>

<div class="modal fade" id="{{ $modal_id }}" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">{{ $modal_label }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{{ $form_url }}" method="POST">
                {{ csrf_field() }}
                <input type="hidden" name="category_id" value="{{ $category_id }}">
                <input type="hidden" name="_method" value="{{ $form_method }}">

                <div class="modal-body">
                    <div class="form-group">
                        <label for="name">{{ _i('Name') }}</label>
                        <input type="text" class="form-control" name="name" id="name" value="{{ $actual_name }}" required autocomplete="false">
                    </div>

                    <div class="form-group">
                        <label for="notices_recipient">{{ _i('Notices Recipient') }}</label>
                        <input type="text" class="form-control" name="notices_recipient" id="notices_recipient" value="{{ $actual_referent }}" required autocomplete="false">
                        <small class="form-text text-muted">
                            {{ _i('Comma-separated recipients (foo@example.com, bar@example.com).') }}
                        </small>
                    </div>

                    @if(App\Config::getConfig('checklist_times'))
                        <div class="form-group mt-4">
                            <table class="table hours-grid">
                                <thead>
                                    <th width="12.5%">&nbsp;</th>
                                    @foreach(App\Checklist::availableDays() as $day => $label)
                                        <th width="12.5%">{{ $label }}</th>
                                    @endforeach
                                </thead>
                                <tbody>
                                    @foreach(App\Checklist::availableHours() as $hour)
                                        <tr>
                                            <th>{{ $hour }}</th>
                                            @foreach(App\Checklist::availableDays() as $day => $label)
                                                <td>
                                                    <input class="form-control" type="checkbox" name="hours[]" value="{{ sprintf('%s_%s', $day, $hour) }}" {{ $checklist && $checklist->hasHour($day, $hour) ? 'checked' : '' }}>
                                                </td>
                                            @endforeach
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    @endif
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{{ _i('Close') }}</button>
                    <button type="submit" class="btn btn-success">{{ _i('Save') }}</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/checklist/index.blade.php
@extends('app')

@section('contents')
    @if($pending->isEmpty() == false)
        <div class="row">
            <div class="col">
                <div class="list-group mb-4">
                    <a href="#" class="list-group-item list-group-item-danger">{{ _i('To be completed') }}</a>

                    @foreach($pending as $pend)
                        <a href="{{ route('history.edit', ['history' => $pend->id]) }}" class="list-group-item list-group-item-action">
                            {{ $pend->checklist->name }}

                            <small class="float-end">
                                {{ _i('Last Updated On: %s', date('d/m/Y G:i:s', strtotime($pend->updated_at))) }}
                            </small>
                        </a>
                    @endforeach
                </div>
            </div>
        </div>
    @endif

    <div class="row">
        <div class="col">
            @if($categories->isEmpty())
                <div class="alert alert-info">
                    <p>
                        {{ _i('There are not checklists yet to fill!') }}
                    </p>
                    @if(Auth::user()->hasPermission('checklists'))
                        <p>
                            {!! _i('Go to <a href="%s">Admin panel</a> to create new categories and checklists, and remember to also add items to be assigned!', [route('category.index')]) !!}
                        </p>
                        @endif
                </div>
            @else
                @foreach($categories as $category)
                    <div class="list-group mb-4">
                        <a href="#" class="list-group-item list-group-item-action active">{{ $category->name }}</a>

                        @foreach($category->checklists as $checklist)
                            <a href="{{ route('history.create', ['checkid' => $checklist->id]) }}" class="list-group-item list-group-item-action">
                                {{ $checklist->name }}

                                <small class="float-end">
                                    {{ _i('Last Filled On: %s', $checklist->histories()->count() == 0 ? _i('Never') : date('d/m/Y G:i:s', strtotime($checklist->histories()->first()->date))) }}
                                </small>
                            </a>
                        @endforeach
                    </div>
                @endforeach
            @endif
        </div>
    </div>
@endsection

resources/views/checklist/show.blade.php
@if($checklist == null && $items->isEmpty() && $categories->isEmpty())
    <div class="row">
        <div class="col">
            <div class="alert alert-info">
                {{ _i('Here you will assign items to checklists, sort them, and organize them as you prefer.') }}
            </div>
        </div>
    </div>
@else
    <div class="row">
        <div class="col">
            <div class="alert alert-info">
                {{ _i('Drag and drop items on the preferred categories/slots to add them to the related checklists.') }}
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-3">
            @if($items->isEmpty())
                <div class="alert alert-info">
                    <p>
                        {{ _i('There are not items.') }}
                    </p>
                    <p>
                        {!! _i('You have first to <a href="%s">create items</a> to be assigned to the checklist.', [route('category.index', ['tab' => 'items'])]) !!}
                    </p>
                </div>
            @else
                <input type="text" class="form-control filter-group" data-target="#disposable-items" placeholder="{{ _i('Filter Items') }}">
                <br>

                <ul class="list-group" id="disposable-items">
                    @foreach($items as $item)
                        <li class="list-group-item" data-item-id="{{ $item->id }}">
                            <span class="oi oi-arrow-right" title="{{ _i('Drag to Add') }}"></span>
                            <span class="name">{{ $item->name }}</span>
                        </li>
                    @endforeach
                </ul>
            @endif
        </div>
        <div class="col-md-6">
            @if($checklist == null)
                <div class="alert alert-warning">
                    <p>
                        {{ _i('No checklist selected.') }}
                    </p>

                    @if($categories->isEmpty())
                        <p>
                            {!! _i('You have first to <a href="%s">create a category</a> and a checklist at least.', [route('category.index', ['tab' => 'categories'])]) !!}
                        </p>
                    @else
                        @if(App\Checklist::count() == 0)
                            <p>
                                {{ _i('You have to create at least a checklist.') }}
                            </p>
                        @else
                            <p>
                                {{ _i('Click on one of the checklists on the right to activate it and populate with items.') }}
                            </p>
                        @endif
                    @endif
                </div>
            @else
                <li class="list-group-item checklist-row" data-update-url="{{ route('checklist.update', $checklist->id) }}">
                    <span class="action-icons float-end">
                        <button type="button" class="btn btn-primary float-end" data-bs-toggle="modal" data-bs-target="#createSlot-{{ $checklist->id }}">{{ _i('Create New Slot') }}</button>
                    </span>

                    <h3>{{ $checklist->name }}</h3>

                    <div class="clearfix"></div>
                    <hr>

                    <ul class="list-group sortable" data-sorted-callback="updateSlots">
                        @foreach($checklist->slots as $slot)
                            @include('slot.show', ['slot' => $slot])
                        @endforeach
                    </ul>
                </li>

                @include('slot.edit', ['checklist' => $checklist, 'slot' => null])
            @endif
        </div>
        <div class="col-md-3">
            @if($categories->isEmpty())
                <div class="alert alert-info">
                    {{ _i('There are not categories.') }}
                </div>
            @else
                <p class="text-end">
                    {{ _i('Checklists') }}
                </p>
                <div class="nav flex-column nav-pills">
                    @foreach($categories as $category)
                        <a class="list-group-item list-group-item-light">{{ $category->name }}</a>

                        @if($category->checklists->isEmpty())
                            <a class="nav-link">
                                {{ _i('There are no checklists in this category') }}
                            </a>
                        @else
                            @foreach($category->checklists as $iter_checklist)
                                <a class="nav-link {{ $checklist != null && $iter_checklist->id == $checklist->id ? 'active' : '' }}" href="{{ route('category.index', ['tab' => 'distribution', 'checklist' => $iter_checklist->id]) }}">
                                    {{ $iter_checklist->name }}
                                </a>
                            @endforeach
                        @endif
                    @endforeach
                </div>
            @endif
        </div>
    </div>

    <div id="templates" hidden>
        <ul class="item-in-slot">
            <li class="list-group-item" data-item-id="">
                <span class="name"></span>
                <span class="action-icons float-end">
                    <span class="oi oi-trash" title="{{ _i('Remove Object') }}"></span>
                    <span class="oi oi-resize-height" title="{{ _i('Drag to Sort') }}"></span>
                </span>
            </li>
        </ul>
    </div>
@endif